main: com.hazebyte.base.demo.Core
name: BaseTest
version: '0.0.0'
description: An example plugin for the library, Base
load: POSTWORLD
author: imWillX
commands:
  base:
    description: Example command
    usage: /base
